name: Docker Deployment

on:
  push:
    branches:
      - master  # This specifies the branch for which the workflow will run

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.sukritya }}
          password: ${{ secrets.Luni04suk@d }}

      - name: Build and push Docker image
        run: |
          docker build -t sukritya/my-docker-project .
          docker push sukritya/my-docker-project
