name: Deploy to Private Server

on:  
  push:
    branches:
      - main  # Adjust to your preferred branch if needed

jobs:
  deploy:
    runs-on: self-hosted  # This tells GitHub to use your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull latest Docker image
        run: docker pull your-docker-image:latest

      - name: Stop old container
        run: |
          docker stop my-container || true
          docker rm my-container || true

      - name: Run new Docker container
        run: |
          docker run -d -p 8080:80 --name my-container your-docker-image:latest
